apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx
data:
  default.conf: |
    server {
      listen 8080;
      server_name _;
      root /usr/share/nginx/html;
      server_tokens off;
      add_header X-Robots-Tag "noindex, nofollow" always;
      add_header Cache-Control "no-store" always;
      location / { try_files $uri $uri/ =404; }
    }
